version: '3.8'

services:
  backend:
    build: ./backend
    container_name: pharmacy-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_DB=pharmacy
      - POSTGRES_USER=pharmacy
      - POSTGRES_PASSWORD=pharmacy
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: pharmacy-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: pharmacy-db
    environment:
      POSTGRES_DB: pharmacy
      POSTGRES_USER: pharmacy
      POSTGRES_PASSWORD: pharmacy
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: